import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <div
          className="bg-neutral-100
          dark:bg-neutral-900
          dark:text-neutral-100"
        >
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
